//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable
    {
        public int StaffNum { get; set; }
        public string StaffImg { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> DepartmentNum { get; set; }
        public int StaffAge { get; set; }
        public string StaffSex { get; set; }
        public string StaffIphone { get; set; }
        public string StaffAddress { get; set; }
        public System.DateTime StaffStime { get; set; }
        public int StaffWages { get; set; }
        public Nullable<int> JobNum { get; set; }
        public string Remarks { get; set; }
    }
}
